server:
  port: 8083

spring:
  application:
    name: EligibilityDetermination
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/datacollections
    username: root
    password: Abdu1992$
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

